find ./srt/databases/*   -delete
find ./ngx/databases/*   -delete
find ./wind/databases/*   -delete
find ./kapella/databases/*   -delete
find ./chen/databases/*   -delete
find ./concept/databases/*   -delete
find ./angflat/databases/*   -delete
find ./sb/databases/*   -delete
find ./notika/databases/*   -delete
find ./kit/databases/*   -delete
find ./bulma/databases/*   -delete
find ./desk/databases/*   -delete
find ./bulmaadmin/databases/*   -delete
find ./vuenotus/databases/*   -delete
find ./vuestic/databases/*   -delete
find ./lte3/databases/*   -delete
find ./tailwind/databases/*   -delete
find ./vuetim/databases/*   -delete
find ./volt/databases/*   -delete
find ./octopus/databases/*   -delete
find ./bulma-ad/databases/*   -delete
find ./corona/databases/*   -delete
find ./gentelella/databases/*   -delete
